version: "3.9"
services:
  yourarch:
    image: victor141516/yourarch
    restart: unless-stopped
    networks:
      - default
      - caddywork
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
  
  postgres:
    image: postgres
    restart: unless-stopped
    networks:
      - default
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./database:/var/lib/postgresql/data/pgdata


networks:
  caddywork:
    external: true
    name: caddywork
