version: "3.9"
services:
  yourarch:
    image: victor141516/yourarch
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 43000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
    volumes:
      - ".:/app"
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data/pgdata
